# Template for building ADF ARM templates for an environment

parameters:
  - name: environment
    type: string

  - name: artifactName
    type: string

stages:
  - stage: Build_${{ replace(parameters.environment, '-', '_') }}
    displayName: Build ${{ parameters.environment }}
    variables:
      - template: /.azuredevops/variables/${{ parameters.environment }}.yml
    jobs:
      - job: BuildArmTemplates
        displayName: Validate and Generate ARM Templates
        steps:
          - task: UseNode@1
            inputs:
              version: 20.x
            displayName: Install Node.js

          - task: Npm@1
            inputs:
              command: install
              workingDir: $(Build.SourcesDirectory)/.azuredevops
            displayName: Install npm packages

          - task: Npm@1
            inputs:
              command: custom
              workingDir: $(Build.SourcesDirectory)/.azuredevops
              customCommand: >-
                run build validate
                $(Build.SourcesDirectory)/adf
                /subscriptions/${{ variables.subscriptionId }}/resourceGroups/${{ variables.resourceGroupName }}/providers/Microsoft.DataFactory/factories/${{ variables.dataFactoryName }}
            displayName: Validate ADF resources

          - task: Npm@1
            inputs:
              command: custom
              workingDir: $(Build.SourcesDirectory)/.azuredevops
              customCommand: >-
                run build export
                $(Build.SourcesDirectory)/adf
                /subscriptions/${{ variables.subscriptionId }}/resourceGroups/${{ variables.resourceGroupName }}/providers/Microsoft.DataFactory/factories/${{ variables.dataFactoryName }}
                "ArmTemplate"
            displayName: Generate ARM templates

          - task: CopyFiles@2
            inputs:
              SourceFolder: $(Build.SourcesDirectory)/.azuredevops/ArmTemplate
              Contents: '**/*.*'
              TargetFolder: $(Build.ArtifactStagingDirectory)
            displayName: Copy ArmTemplate

          - task: CopyFiles@2
            inputs:
              SourceFolder: $(Build.SourcesDirectory)/.azuredevops/scripts
              Contents: '**/*.ps1'
              TargetFolder: $(Build.ArtifactStagingDirectory)
            displayName: Copy deployment scripts

          - task: CopyFiles@2
            inputs:
              SourceFolder: $(Build.SourcesDirectory)/.azuredevops/parameters
              Contents: ARM.parameters.json
              TargetFolder: $(Build.ArtifactStagingDirectory)/parameters
            displayName: Copy parameter file

          - script: ls -laR $(Build.ArtifactStagingDirectory)
            displayName: List artifact staging directory

          - publish: $(Build.ArtifactStagingDirectory)
            artifact: ${{ parameters.artifactName }}
            displayName: Publish ARM templates