# Template for building ADF ARM templates for an environment

parameters:
  - name: environment
    type: string

  - name: artifactName
    type: string

stages:
  - stage: Build_${{ replace(parameters.environment, '-', '_') }}
    displayName: Build ${{ parameters.environment }}
    variables:
      - template: /.azuredevops/variables/${{ parameters.environment }}.yml
    jobs:
      - job: BuildArmTemplates
        displayName: Validate and Generate ARM Templates
        steps:
          - task: UseNode@1
            inputs:
              version: 20.x
            displayName: Install Node.js

          - task: Npm@1
            inputs:
              command: ci
              workingDir: $(Build.SourcesDirectory)/.azuredevops
            displayName: Install npm packages

          - task: Npm@1
            inputs:
              command: custom
              customCommand: run build validate $(Build.SourcesDirectory)/adf /subscriptions/$(subscriptionId)/resourceGroups/$(resourceGroupName)/providers/Microsoft.DataFactory/factories/$(dataFactoryName) --prefix $(Build.SourcesDirectory)/.azuredevops
            displayName: Validate ADF resources

          - task: Npm@1
            inputs:
              command: custom
              customCommand: run build export $(Build.SourcesDirectory)/adf /subscriptions/$(subscriptionId)/resourceGroups/$(resourceGroupName)/providers/Microsoft.DataFactory/factories/$(dataFactoryName) $(Build.ArtifactStagingDirectory) --prefix $(Build.SourcesDirectory)/.azuredevops
            displayName: Generate ARM templates

          - task: CopyFiles@2
            inputs:
              SourceFolder: $(Build.SourcesDirectory)/.azuredevops/scripts
              Contents: "**/*.ps1"
              TargetFolder: $(Build.ArtifactStagingDirectory)
            displayName: Copy deployment scripts

          - task: CopyFiles@2
            inputs:
              SourceFolder: $(Build.SourcesDirectory)/.azuredevops/parameters
              Contents: "**/*.json"
              TargetFolder: $(Build.ArtifactStagingDirectory)/parameters
            displayName: Copy parameter files

          - publish: $(Build.ArtifactStagingDirectory)
            artifact: ${{ parameters.artifactName }}
            displayName: Publish ARM templates
