# Template for deploying ADF to an environment
# Uses standard templates (for <256 resources)

parameters:
  - name: environment
    type: string

  - name: artifactName
    type: string

stages:
  - stage: ${{ replace(parameters.environment, '-', '_') }}
    displayName: Deploy to ${{ parameters.environment }}
    variables:
      - template: /.azuredevops/variables/${{ parameters.environment }}.yml
    jobs:
      - deployment: DeployADF
        displayName: Deploy ADF to ${{ parameters.environment }}
        pool: mdp-tdcpl-azdo-euw-dev
        environment: ${{ parameters.environment }}
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: ${{ parameters.artifactName }}
                  displayName: Download ARM templates

                # Pre-deployment: Stop triggers
                - task: AzurePowerShell@5
                  displayName: Pre-deployment - Stop triggers
                  inputs:
                    azureSubscription: ${{ variables.azureServiceConnection }}
                    ScriptType: FilePath
                    ScriptPath: $(Pipeline.Workspace)/${{ parameters.artifactName }}/PrePostDeploymentScript.Ver2.ps1
                    ScriptArguments: >
                      -ArmTemplate "$(Pipeline.Workspace)/${{ parameters.artifactName }}/ARMTemplateForFactory.json"
                      -ArmTemplateParameters "$(Pipeline.Workspace)/${{ parameters.artifactName }}/ARMTemplateParametersForFactory.json"
                      -ResourceGroupName ${{ variables.resourceGroupName }}
                      -DataFactoryName ${{ variables.dataFactoryName }}
                      -PreDeployment $true
                      -DeleteDeployment $false
                    azurePowerShellVersion: LatestVersion
                    pwsh: true

                # Deploy ARM template
                - task: AzureResourceManagerTemplateDeployment@3
                  displayName: Deploy ARM template
                  inputs:
                    azureResourceManagerConnection: ${{ variables.azureServiceConnection }}
                    subscriptionId: ${{ variables.subscriptionId }}
                    resourceGroupName: ${{ variables.resourceGroupName }}
                    location: ${{ variables.location }}
                    csmFile: $(Pipeline.Workspace)/${{ parameters.artifactName }}/ARMTemplateForFactory.json
                    csmParametersFile: $(Pipeline.Workspace)/${{ parameters.artifactName }}/${{ parameters.environment }}.parameters.json
                    # overrideParameters: >
                    #   -some_password "password123"
                    deploymentMode: Incremental

                # Post-deployment: Start triggers and cleanup
                - task: AzurePowerShell@5
                  displayName: Post-deployment - Start triggers and cleanup
                  condition: succeeded()
                  inputs:
                    azureSubscription: ${{ variables.azureServiceConnection }}
                    ScriptType: FilePath
                    ScriptPath: $(Pipeline.Workspace)/${{ parameters.artifactName }}/PrePostDeploymentScript.Ver2.ps1
                    ScriptArguments: >
                      -ArmTemplate "$(Pipeline.Workspace)/${{ parameters.artifactName }}/ARMTemplateForFactory.json"
                      -ArmTemplateParameters "$(Pipeline.Workspace)/${{ parameters.artifactName }}/ARMTemplateParametersForFactory.json"
                      -ResourceGroupName ${{ variables.resourceGroupName }}
                      -DataFactoryName ${{ variables.dataFactoryName }}
                      -PreDeployment $false
                      -DeleteDeployment $true
                    azurePowerShellVersion: LatestVersion
                    pwsh: true
