# Template for deploying ADF to an environment

parameters:
  - name: environment
    type: string

  - name: artifactName
    type: string

stages:
  - stage: ${{ replace(parameters.environment, '-', '_') }}
    displayName: Deploy to ${{ parameters.environment }}
    variables:
      - template: /.azuredevops/variables/${{ parameters.environment }}.yml
    jobs:
      - deployment: DeployADF
        displayName: Deploy ADF to ${{ parameters.environment }}
        environment: ${{ parameters.environment }}
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: ${{ parameters.artifactName }}
                  displayName: Download ARM templates

                # Pre-deployment: Stop triggers
                - task: AzurePowerShell@5
                  displayName: Pre-deployment - Stop triggers
                  inputs:
                    azureSubscription: ${{ variables.azureServiceConnection }}
                    ScriptType: FilePath
                    ScriptPath: $(Pipeline.Workspace)/${{ parameters.artifactName }}/PrePostDeploymentScript.Ver2.ps1
                    ScriptArguments: >
                      -ArmTemplate "$(Pipeline.Workspace)/${{ parameters.artifactName }}/linkedTemplates/ArmTemplate_master.json"
                      -ArmTemplateParameters "$(Pipeline.Workspace)/${{ parameters.artifactName }}/parameters/${{ parameters.environment }}.parameters.json"
                      -ResourceGroupName ${{ variables.resourceGroupName }}
                      -DataFactoryName ${{ variables.dataFactoryName }}
                      -PreDeployment $true
                      -DeleteDeployment $false
                    azurePowerShellVersion: LatestVersion
                    pwsh: true

                # Deploy ARM template using linked templates
                - task: AzureResourceManagerTemplateDeployment@3
                  displayName: Deploy ARM template
                  inputs:
                    azureResourceManagerConnection: ${{ variables.azureServiceConnection }}
                    subscriptionId: ${{ variables.subscriptionId }}
                    resourceGroupName: ${{ variables.resourceGroupName }}
                    location: westeurope
                    csmFile: $(Pipeline.Workspace)/${{ parameters.artifactName }}/linkedTemplates/ArmTemplate_master.json
                    csmParametersFile: $(Pipeline.Workspace)/${{ parameters.artifactName }}/parameters/${{ parameters.environment }}.parameters.json
                    overrideParameters: -factoryName "${{ variables.dataFactoryName }}" -some_fileserver_password (ConvertTo-SecureString "adfhubspokepoc123!" -AsPlainText -Force)
                    deploymentMode: Incremental
                    deploymentOutputs: ArmOutputs

                # Post-deployment: Start triggers and cleanup
                - task: AzurePowerShell@5
                  displayName: Post-deployment - Start triggers and cleanup
                  condition: succeeded()
                  inputs:
                    azureSubscription: ${{ variables.azureServiceConnection }}
                    ScriptType: FilePath
                    ScriptPath: $(Pipeline.Workspace)/${{ parameters.artifactName }}/PrePostDeploymentScript.Ver2.ps1
                    ScriptArguments: >
                      -ArmTemplate "$(Pipeline.Workspace)/${{ parameters.artifactName }}/linkedTemplates/ArmTemplate_master.json"
                      -ArmTemplateParameters "$(Pipeline.Workspace)/${{ parameters.artifactName }}/parameters/${{ parameters.environment }}.parameters.json"
                      -ResourceGroupName ${{ variables.resourceGroupName }}
                      -DataFactoryName ${{ variables.dataFactoryName }}
                      -PreDeployment $false
                      -DeleteDeployment $true
                    azurePowerShellVersion: LatestVersion
                    pwsh: true